spring:
  profiles:
    active: test
  application:
    name: User Management
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

# ======================================
# = Paging Settings
# ======================================
paging:
  size: 10

# ======================================
# = Pagehelper Settings
# ======================================
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
