spring:
  profiles:
    active: test
  application:
    name: User Management
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

# ======================================
# = Paging settings
# ======================================
paging:
  size: 5

